[buildPlans.sevka]
family = "sevka"
spacing = "fixed"
serifs = "sans"
no-cv-ss = true
export-glyph-names = false

[buildPlans.sevka.variants.design]
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-j = "serifless"
capital-q = "straight"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "double-storey-tailed"
d = "tailed-serifless"
e = "flat-crossbar"
f = "serifed"
g = "double-storey-open"
i = "serifed"
j = "serifed"
l = "serifed-flat-tailed"
m = "normal"
n = "straight"
r = "compact"
s = "serifless"
t = "flat-hook"
u = "tailed"
y = "straight-turn"
z = "straight-serifless-with-horizontal-crossbar"
eszet = "longs-s-lig-descending"
lower-lambda = "straight-turn"
cyrl-capital-ze = "unilateral-serifed"
cyrl-ze = "unilateral-serifed"
zero = "dotted"
one = "base"
four = "open"
six = "open-contour"
seven = "bend-crossbar-serifed"
nine = "open-contour"
asterisk = "penta-low"
underscore = "low"
caret = "high"
paren = "large-contour"
number-sign = "upright-tall"
at = "fourfold-solid-inner-tall"
dollar = "open"
cent = "open"
percent = "dots"
punctuation-dot = "square"
diacritic-dot = "square"

[buildPlans.sevka.variants.italic]
a = "single-storey-earless-corner-tailed"
e = "rounded"
f = "tailed"
i = "tailed-serifed"
k = "diagonal-tailed-cursive-serifless"
m = "tailed"
n = "tailed"
r = "earless-rounded"
t = "diagonal-tailed"
u = "toothless-rounded"
v = "cursive"
w = "cursive"
x = "cursive"

[buildPlans.sevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.sevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.sevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.sevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
