[buildPlans.sevka]
family = "sevka"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

  [buildPlans.sevka.variants]
  inherits = "ss15"

    [buildPlans.sevka.variants.design]
    capital-q = "crossing-baseline"
    lower-lambda = "straight-turn"
    zero = "slashed-cutout"
    one = "base"
    four = "open"
    six = "open-contour"
    seven = "straight-serifless-crossbar"
    nine = "open-contour"
    diacritic-dot = "square"
    punctuation-dot = "square"
    asterisk = "penta-low"
    underscore = "low"
    caret = "high"
    paren = "large-contour"
    number-sign = "upright-tall"
    at = "fourfold-solid-inner-tall"
    dollar = "open"
    percent = "dots"
    cent = "open"
    micro-sign = "tailed-serifless"

    [buildPlans.sevka.variants.italic]
    a = "single-storey-earless-corner-tailed"
    e = "rounded"
    f = "tailed"
    i = "tailed-serifed"
    k = "diagonal-tailed-cursive-serifless"
    r = "earless-rounded-serifless"
    t = "diagonal-tailed"
    x = "cursive"

[buildPlans.sevka.weights.regular]
shape = 400
menu = 400
css = 400

[buildPlans.sevka.weights.bold]
shape = 700
menu = 700
css = 700

[buildPlans.sevka.slopes.upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.sevka.slopes.italic]
angle = 9.4
shape = "italic"
menu = "italic"
css = "italic"
